### ISSUE TITLE
Error when running worker.py

### ISSUE THREAD

**Issue by vaibhavmagarwal** [adusca/pulse_actions#3]
``` python
$ python pulse_actions/worker.py
INFO:	 Listening on exchange/treeherder/v1/job-actions, with topic buildbot.#.#
Traceback (most recent call last):
  File "pulse_actions/worker.py", line 87, in <module>
    main()
  File "pulse_actions/worker.py", line 83, in main
    dry_run=True)
  File "pulse_actions/worker.py", line 56, in run_pulse
    pulse.listen()
  File "build/bdist.macosx-10.10-intel/egg/mozillapulse/consumers.py", line 149, in listen
  File "/Users/vagrawal/pulse_actions/venv/lib/python2.7/site-packages/kombu-3.0.26-py2.7.egg/kombu/abstract.py", line 66, in __call__
    return self.bind(channel)
  File "/Users/vagrawal/pulse_actions/venv/lib/python2.7/site-packages/kombu-3.0.26-py2.7.egg/kombu/abstract.py", line 70, in bind
    return copy(self).maybe_bind(channel)
  File "/Users/vagrawal/pulse_actions/venv/lib/python2.7/site-packages/kombu-3.0.26-py2.7.egg/kombu/abstract.py", line 75, in maybe_bind
    self._channel = maybe_channel(channel)
  File "/Users/vagrawal/pulse_actions/venv/lib/python2.7/site-packages/kombu-3.0.26-py2.7.egg/kombu/connection.py", line 1054, in maybe_channel
    return channel.default_channel
  File "/Users/vagrawal/pulse_actions/venv/lib/python2.7/site-packages/kombu-3.0.26-py2.7.egg/kombu/connection.py", line 756, in default_channel
    self.connection
  File "/Users/vagrawal/pulse_actions/venv/lib/python2.7/site-packages/kombu-3.0.26-py2.7.egg/kombu/connection.py", line 741, in connection
    self._connection = self._establish_connection()
  File "/Users/vagrawal/pulse_actions/venv/lib/python2.7/site-packages/kombu-3.0.26-py2.7.egg/kombu/connection.py", line 696, in _establish_connection
    conn = self.transport.establish_connection()
  File "/Users/vagrawal/pulse_actions/venv/lib/python2.7/site-packages/kombu-3.0.26-py2.7.egg/kombu/transport/pyamqp.py", line 116, in establish_connection
    conn = self.Connection(**opts)
  File "/Users/vagrawal/pulse_actions/venv/lib/python2.7/site-packages/amqp-1.4.6-py2.7.egg/amqp/connection.py", line 180, in __init__
    (10, 30),  # tune
  File "/Users/vagrawal/pulse_actions/venv/lib/python2.7/site-packages/amqp-1.4.6-py2.7.egg/amqp/abstract_channel.py", line 67, in wait
    self.channel_id, allowed_methods)
  File "/Users/vagrawal/pulse_actions/venv/lib/python2.7/site-packages/amqp-1.4.6-py2.7.egg/amqp/connection.py", line 240, in _wait_method
    self.method_reader.read_method()
  File "/Users/vagrawal/pulse_actions/venv/lib/python2.7/site-packages/amqp-1.4.6-py2.7.egg/amqp/method_framing.py", line 189, in read_method
    raise m
IOError: Socket closed

```

I get the above error on running worker.py

**Comment by adusca** [comment]
Sorry, I must update the docs. You need to have environment variables PULSE_USER and PULSE_PW set up (you'll need to create an user in https://pulse.mozilla.org ).

**Comment by vaibhavmagarwal** [comment]
I adjusted 'username' and 'password' to mine, now it just prints
``` python
$ python pulse_actions/worker.py
INFO:	 Listening on exchange/treeherder/v1/job-actions, with topic buildbot.#.#
```
It does not catch any actions whereas https://tools.taskcluster.net/pulse-inspector/#!%28%28exchange:exchange/treeherder/v1/job-actions,routingKeyPattern:buildbot.%23.%23%29%29 catches the retrigger and cancel action

**Comment by adusca** [comment]
Can you look at https://pulse.mozilla.org/queues and see if a queue was created?

**Comment by vaibhavmagarwal** [comment]
Yes, it shows a queue is created of 296 messages. What does that signify? It does not print any action on terminal, even though I have added LOG.info commands.

**Comment by vaibhavmagarwal** [comment]
Now it is printing logs, which previously it wasn't.  I think when the queue messages reached 300, the logs started then. It may be some expected behaviour?

**Comment by vaibhavmagarwal** [comment]
Heh, there was some problem before I guess, now it has *magically* disappeared. Now the messages are printed properly. I guess we should let this issue open for some fixes in documentation.

**Comment by adusca** [comment]
pulse_actions creates a queue (queue/{user}/pulse_actions) on Pulse. The exchange messages arrive on the queue and then pulse_actions reads from it. It is usually able to start processing the messages as soon as the first one arrives, I never had to wait for 300 messages.

**Comment by adusca** [comment]
I updated https://github.com/adusca/pulse_actions/blob/master/README.rst#running , does it work for you?

**Comment by vaibhavmagarwal** [comment]
Yeah, it does.

**Comment by vaibhavmagarwal** [comment]
I think we can close this issue, as adequate documentation has been added.
